# -*- coding: utf-8 -*-
"""Interference (UTS MD).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZgDZDJ9apSJnP0imTabmtdOFME_mqMsc
"""

import pandas as pd
from loan_model_pipeline import LoanModelPipeline

model_pipeline = LoanModelPipeline(model_type='xgboost')
X_train, X_test, y_train, y_test = model_pipeline.load_and_prepare_data('Dataset_A_loan.csv')
model_pipeline.train(X_train, y_train)

sample_data = X_test.iloc[[0]]
result = model_pipeline.predict(sample_data)

label_map = {1: 'DISETUJUI', 0: 'DITOLAK'}
status = label_map[result["prediction"][0]]
prob = result["probability"][0]

print("Hasil Prediksi:", status)
print(f"Probabilitas disetujui: {prob:.2%}")